// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ToolComponentImport = new FileRoute('/tool').createRoute()
const GuideComponentImport = new FileRoute('/guide').createRoute()

// Create/Update Routes

const ToolComponentRoute = ToolComponentImport.update({
  path: '/tool',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/tool.component'),
    'component',
  ),
})

const GuideComponentRoute = GuideComponentImport.update({
  path: '/guide',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/guide.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      preLoaderRoute: typeof GuideComponentImport
      parentRoute: typeof rootRoute
    }
    '/tool': {
      preLoaderRoute: typeof ToolComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  GuideComponentRoute,
  ToolComponentRoute,
])
